resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'
  demands: azureps

steps:
- task: DownloadSecureFile@1
  name: sshkey
  displayName: 'Download SSH private key'
  inputs:
    secureFile: 'azure-devops-ssh'

- task: DownloadSecureFile@1
  name: sshkeypub
  displayName: 'Download SSH public key'
  inputs:
    secureFile: 'azure-devops-ssh-pub'

- task: AzurePowerShell@5
  displayName: 'Running tests'
  inputs:
    azureSubscription: 'AzureSubscription'
    ScriptPath: 'FortiGate/A-Single-VM/test/invokePester.ps1'
    ScriptArguments: '-templatename FortiGate/A-Single-VM -sshkey $(sshkey.secureFilePath) -sshkeypub $(sshkeypub.secureFilePath)'
    azurePowerShellVersion: LatestVersion
    pwsh: true

- task: PublishTestResults@2
  displayName: 'Publish ARM TTK results'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/*-armttk.xml'
    testRunTitle: 'ARM TTK verification'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TEST-*.xml'
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'ARM template and deployment test'

trigger:
  branches:
    include:
    - main
    - dev
  paths:
    exclude:
    - FortiGate/A-Single-VM/*.md
    include:
    - FortiGate/A-Single-VM/*
